<?php
/*=======================================================\
|                        FrontHrm                        |
|--------------------------------------------------------|
|   Creator: Phương                                      |
|   Date :   09-07-2017                                  |
|   Description: Frontaccounting Payroll & Hrm Module    |
|   Free software under GNU GPL                          |
|                                                        |
\=======================================================*/
include_once($path_to_root."/modules/FrontHrm/includes/db/template_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/templete_pmt_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/employee_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/department_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_scale_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/overtime_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/attendance_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/daily_attendance_db.inc");
// include_once($path_to_root."/modules/FrontHrm/includes/db/emp_daily_attendance_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/detail_employee_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/account_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_structure_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/payslip_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_template.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/holiday_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/unit_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/shift_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/payment_string_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_structure_emp_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/overtime_tmp_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/leave_ledger_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/emp_shift_list_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/pre_salary_sheet_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/emp_pre_salarysheet_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/emp_pre_salarysheet_temp_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/emp_salary_increment_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/section_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/increment_process_db.inc");
include_once($path_to_root."/modules/FrontHrm/includes/db/salary_increment_by_hiredate_db.inc");

